---
title: "p8105_mtp_tk2886"
author: "Tanvir Khan"
date: 2021-10-21
output: github_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r echo = FALSE, message = FALSE}
library(tidyverse)
library(p8105.datasets)
library(ggridges)
library(readxl)

## Set Global Options 
knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6, 
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```




# Problem 1

### Loading the p8105_mtp_data.xlsx data set and cleaning the data set 
```{r}
mtp_df <-
  read_excel(
    "./data/p8105_mtp_data.xlsx",
    sheet = "this one",
    range = "A9:I1230") %>%
  janitor::clean_names()
```




### Replacing numerical codes with the real representation and converting data types to the correct data types and arranging the table by gender and age. 
```{r}
eop_dfc <- 
  mtp_df %>%
  mutate(
     sex = recode(sex, "0" = "Female", "1" = "Male"),
     age_group = recode(age_group,
                       "2" = "18-30", 
                       "3" = "31-40", 
                       "4" = "41-50",
                       "5" = "51-60", 
                       "6" = "60+",
                       "7" = "60+", 
                       "8" = "60+"), 
    eop_size_mm = replace(eop_size_mm, is.na(eop_size_mm), "0"),
    eop_size = recode(eop_size,
                      "0" = "0-5",
                      "1" = "5-10",
                      "2" = "10-15",
                      "3" = "15-20",
                      "4" = "20-25",
                      "5" = "25+"
                      ),
    eop_visibility_classification = recode(eop_visibility_classification,
                      "0" = "eop size 0 mm",
                      "1" = "0 < eop size mm <= 5",
                      "2" = "eop size >= 5 mm"),
    fhp_category = recode(fhp_category,
                          "0" = "0-10",
                          "1" = "10-20",
                          "2" = "20-30",
                          "3" = "30-40",
                          "4" = "40-50",
                          "5" = "50-60",
                          "6" = "60-70",
                          "7" = "70-80"),
    sex = factor(sex, levels = c("Female",
                                  "Male")), 
    age_group = factor(age_group, levels = c("18-30", 
                                             "31-40",
                                              "41-50", 
                                             "51-60",
                                              "60+")),
    eop_size = factor(eop_size, levels = c(
                      "0-5",
                      "5-10",
                      "10-15",
                      "15-20",
                      "20-25",
                      "25+")), 
    eop_visibility_classification = factor(eop_visibility_classification, levels = c(
      "eop size 0 mm",
      "0 < eop size mm <= 5",
      "eop size >= 5 mm")), 
    age = as.integer(age),
    eop_size_mm = as.double(eop_size_mm)) %>%
  rename(eop_group = eop_size,
         fhp_group = fhp_category) %>%
  drop_na(age_group) %>%
  arrange(sex, age)

eop_dfc
```



```{r}
eop_dfc %>% 
  group_by(sex, age_group) %>% 
  summarise(
    frequency = n()) %>% 
  pivot_wider(
    names_from = sex,
    values_from = frequency) %>% 
  knitr::kable(col.names = c('Age Group', 'Female', 'Male'))
```


```{r}

```


